# Generated by Django 3.2.8 on 2021-10-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer_Name',
        ),
    ]
