# Generated by Django 3.2.8 on 2021-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_whishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
