# Generated by Django 3.2.8 on 2021-12-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211111_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
